### ISSUE TITLE
Paginazione notifiche

### ISSUE THREAD

**Issue by ncanella** [MpStyle/NotificationManager#9]
Se ci sono più pagine le notifiche non vengono ordinate per data decrescente. Ad esempio nella pagina 1 trovo 10 notifiche ordinate per data (OK). Se però vado nella pagina 2 trovo quelle più recenti ordinate sempre per data, ma dovrebbero essere nella pagina 1. Quindi se ci sono 15 notifiche (dove 1 è l'id di quella più vecchia e 15 quello della più recente) la situazione è questa: Pagina 1 -> 10,9,8,...,1 | Pagina 2 -> 15,14,...,11

**Comment by MpStyle** [comment]
Fixed
